version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: allomovie-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: allomovie
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"
    volumes:
      - allomovie_mysql_data:/var/lib/mysql
    networks:
      - allomovie-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

networks:
  allomovie-network:

volumes:
  allomovie_mysql_data:
